/* =========================================================
   CartSys - Script de criação do banco (Firebird 3.0)
   ========================================================= */

/* ---------- SEQUENCES ---------- */
CREATE SEQUENCE SEQ_USUARIOS;
CREATE SEQUENCE SEQ_CLIENTES;
CREATE SEQUENCE SEQ_PRODUTOS;
CREATE SEQUENCE SEQ_VENDAS;
CREATE SEQUENCE SEQ_ITENS_VENDA;
CREATE SEQUENCE SEQ_LOG_ACESSO;
CREATE SEQUENCE SEQ_LOG_NOTIFICACAO;
CREATE SEQUENCE SEQ_MOVIMENTO_FINANCEIRO;

/* ---------- TABELA: USUARIOS ---------- */
CREATE TABLE USUARIOS (
    ID              INTEGER NOT NULL,
    LOGIN           VARCHAR(50)  NOT NULL,
    NOME            VARCHAR(120) NOT NULL,
    SENHA_HASH      VARCHAR(256) NOT NULL,
    SENHA_SALT      VARCHAR(64)  NOT NULL,
    TOTP_SECRET     VARCHAR(64)  NOT NULL,
    E_ADMIN         SMALLINT DEFAULT 0 NOT NULL,
    TENTATIVAS_FALHAS SMALLINT DEFAULT 0 NOT NULL,
    BLOQUEADO       SMALLINT DEFAULT 0 NOT NULL,
    DATA_BLOQUEIO   TIMESTAMP,
    ATIVO           SMALLINT DEFAULT 1 NOT NULL,
    DATA_CRIACAO    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_USUARIOS PRIMARY KEY (ID),
    CONSTRAINT UQ_USUARIOS_LOGIN UNIQUE (LOGIN)
);

/* ---------- TABELA: CLIENTES ---------- */
CREATE TABLE CLIENTES (
    ID              INTEGER NOT NULL,
    NOME            VARCHAR(150) NOT NULL,
    DOCUMENTO       VARCHAR(20),
    EMAIL           VARCHAR(150),
    TELEFONE        VARCHAR(20),
    ENDERECO        VARCHAR(200),
    CIDADE          VARCHAR(100),
    UF              VARCHAR(2),
    ATIVO           SMALLINT DEFAULT 1 NOT NULL,
    DATA_CRIACAO    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (ID)
);

/* ---------- TABELA: PRODUTOS ---------- */
CREATE TABLE PRODUTOS (
    ID              INTEGER NOT NULL,
    DESCRICAO       VARCHAR(150) NOT NULL,
    CODIGO_BARRAS   VARCHAR(30),
    PRECO_VENDA     DECIMAL(15,2) NOT NULL,
    ESTOQUE         INTEGER DEFAULT 0 NOT NULL,
    ATIVO           SMALLINT DEFAULT 1 NOT NULL,
    DATA_CRIACAO    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_PRODUTOS PRIMARY KEY (ID)
);

/* ---------- TABELA: VENDAS ---------- */
/* STATUS: 0 = Pendente | 1 = Quitada | 2 = Cancelada */
CREATE TABLE VENDAS (
    ID              INTEGER NOT NULL,
    ID_CLIENTE      INTEGER NOT NULL,
    ID_USUARIO      INTEGER NOT NULL,
    DATA_VENDA      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    VALOR_TOTAL     DECIMAL(15,2) DEFAULT 0 NOT NULL,
    STATUS          SMALLINT DEFAULT 0 NOT NULL,
    DATA_QUITACAO   TIMESTAMP,
    DATA_CANCELAMENTO TIMESTAMP,
    OBSERVACAO      VARCHAR(500),
    RELATORIO_ENVIADO SMALLINT DEFAULT 0 NOT NULL,
    CONSTRAINT PK_VENDAS PRIMARY KEY (ID),
    CONSTRAINT FK_VENDAS_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID),
    CONSTRAINT FK_VENDAS_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID),
    CONSTRAINT CK_VENDAS_STATUS CHECK (STATUS IN (0,1,2))
);

/* ---------- TABELA: ITENS_VENDA ---------- */
CREATE TABLE ITENS_VENDA (
    ID              INTEGER NOT NULL,
    ID_VENDA        INTEGER NOT NULL,
    ID_PRODUTO      INTEGER NOT NULL,
    QUANTIDADE      INTEGER NOT NULL,
    PRECO_UNITARIO  DECIMAL(15,2) NOT NULL,
    SUBTOTAL        DECIMAL(15,2) NOT NULL,
    CONSTRAINT PK_ITENS_VENDA PRIMARY KEY (ID),
    CONSTRAINT FK_ITENVENDA_VENDA FOREIGN KEY (ID_VENDA) REFERENCES VENDAS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ITENVENDA_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID)
);

/* ---------- TABELA: LOG_ACESSO (auditoria de login) ---------- */
CREATE TABLE LOG_ACESSO (
    ID              INTEGER NOT NULL,
    ID_USUARIO      INTEGER,
    LOGIN_TENTADO   VARCHAR(50) NOT NULL,
    DATA_HORA       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    SUCESSO         SMALLINT DEFAULT 0 NOT NULL,
    MOTIVO_FALHA    VARCHAR(200),
    IP_ORIGEM       VARCHAR(45),
    CONSTRAINT PK_LOG_ACESSO PRIMARY KEY (ID)
);

/* ---------- TABELA: LOG_NOTIFICACAO (controle de e-mail) ---------- */
CREATE TABLE LOG_NOTIFICACAO (
    ID              INTEGER NOT NULL,
    ID_VENDA        INTEGER NOT NULL,
    DESTINATARIO    VARCHAR(150) NOT NULL,
    DATA_ENVIO      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    SUCESSO         SMALLINT DEFAULT 0 NOT NULL,
    MENSAGEM_ERRO   VARCHAR(500),
    CONSTRAINT PK_LOG_NOTIFICACAO PRIMARY KEY (ID),
    CONSTRAINT FK_LOGNOTIF_VENDA FOREIGN KEY (ID_VENDA) REFERENCES VENDAS(ID)
);

/* ---------- TABELA: MOVIMENTO_FINANCEIRO (histórico financeiro) ---------- */
/* TIPO: 0 = Quitacao | 1 = Cancelamento */
CREATE TABLE MOVIMENTO_FINANCEIRO (
    ID              INTEGER NOT NULL,
    ID_VENDA        INTEGER NOT NULL,
    ID_USUARIO      INTEGER NOT NULL,
    TIPO            SMALLINT NOT NULL,
    DATA_HORA       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    VALOR           DECIMAL(15,2) NOT NULL,
    OBSERVACAO      VARCHAR(300),
    CONSTRAINT PK_MOVIMENTO_FINANCEIRO PRIMARY KEY (ID),
    CONSTRAINT FK_MOVFIN_VENDA FOREIGN KEY (ID_VENDA) REFERENCES VENDAS(ID),
    CONSTRAINT FK_MOVFIN_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID)
);

/* ---------- TRIGGERS DE AUTO INCREMENTO ---------- */

SET TERM ^ ;

CREATE TRIGGER TRG_USUARIOS_BI FOR USUARIOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SEQ_USUARIOS;
END^

CREATE TRIGGER TRG_CLIENTES_BI FOR CLIENTES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SEQ_CLIENTES;
END^

CREATE TRIGGER TRG_PRODUTOS_BI FOR PRODUTOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SEQ_PRODUTOS;
END^

CREATE TRIGGER TRG_VENDAS_BI FOR VENDAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SEQ_VENDAS;
END^

CREATE TRIGGER TRG_ITENSVENDA_BI FOR ITENS_VENDA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SEQ_ITENS_VENDA;
END^

CREATE TRIGGER TRG_LOGACESSO_BI FOR LOG_ACESSO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SEQ_LOG_ACESSO;
END^

CREATE TRIGGER TRG_LOGNOTIF_BI FOR LOG_NOTIFICACAO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SEQ_LOG_NOTIFICACAO;
END^

CREATE TRIGGER TRG_MOVFIN_BI FOR MOVIMENTO_FINANCEIRO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR SEQ_MOVIMENTO_FINANCEIRO;
END^

SET TERM ; ^

/* ---------- ÍNDICES ---------- */
CREATE INDEX IDX_VENDAS_STATUS ON VENDAS (STATUS);
CREATE INDEX IDX_VENDAS_CLIENTE ON VENDAS (ID_CLIENTE);
CREATE INDEX IDX_VENDAS_DATA ON VENDAS (DATA_VENDA);
CREATE INDEX IDX_ITENSVENDA_VENDA ON ITENS_VENDA (ID_VENDA);
CREATE INDEX IDX_ITENSVENDA_PRODUTO ON ITENS_VENDA (ID_PRODUTO);
CREATE INDEX IDX_LOGACESSO_LOGIN ON LOG_ACESSO (LOGIN_TENTADO);

/* ---------- USUÁRIO ADMINISTRADOR PADRÃO ----------
   Login: admin / Senha: Admin@123 (ajustar hash real via aplicação)
   O TOTP_SECRET abaixo é apenas um placeholder Base32 de exemplo,
   deve ser gerado de verdade pela aplicação no primeiro cadastro.
------------------------------------------------------ */
INSERT INTO USUARIOS (LOGIN, NOME, SENHA_HASH, SENHA_SALT, TOTP_SECRET, E_ADMIN, ATIVO)
VALUES ('admin', 'Administrador do Sistema', '<GERAR_NA_APLICACAO>', '<GERAR_NA_APLICACAO>', 'JBSWY3DPEHPK3PXP', 1, 1);

COMMIT;